### add user
POST http://127.0.0.1:3000/admin/user
Content-Type: application/json

{
  "email": "424139777@qq.com",
  "password": "5201314",
  "mobile": "12311123233123"
}

### get_users
GET http://127.0.0.1:3000/admin/user
Accept: application/json


### get_usersByPage
GET http://127.0.0.1:3000/admin/user?needPage=1
Accept: application/json


### login User
POST http://127.0.0.1:3000/admin/user/loginByEmail
Content-Type: application/json

{
  "email": "424139777@qq.com",
  "password":"5201314"
}

### register User
POST http://127.0.0.1:3000/admin/user/registerByEmail
Content-Type: application/json

{
  "email": "42412223977227@qq.com",
  "password":"520131422"
}

### login Username
POST http://127.0.0.1:3000/admin/user/loginByUserName
Content-Type: application/json
Cookie: captcha=%242b%2408%24XOb1BFwdMexU0cEkZH94N.EZc%2FtLFWMJi6ZTaAPw3FhioSKfqAZ7a

{
  "username": "15920112861",
  "password":"520131422",
  "code":"4444"
}

### register Username
POST http://127.0.0.1:3000/admin/user/registerByUserName
Content-Type: application/json

{
  "username": "424139772327@qq.com",
  "password":"520131422"
}

### login Username
POST http://127.0.0.1:3000/loginAdmin
Content-Type: application/json

{
  "username": "15920112861",
  "password":"520131422"
}

### login Username
GET http://127.0.0.1:3000/admin/user/getCaptcha
Content-Type: application/json

{
  "username": "15920112861",
  "password":"520131422"
}